parser: 'babel-eslint'
env:
  node: true
  es6: true
extends:
  - 'eslint:recommended'
  - 'airbnb-base'
plugins:
  - 'import'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  quotes:
    - 'error'
    - 'single'
    -
      avoidEscape: true
  no-multiple-empty-lines:
    - 'error'
    -
      max: 2
      maxBOF: 0
      maxEOF: 1
  'import/prefer-default-export': off
  no-unused-expressions: 'off'
  'import/no-extraneous-dependencies':
    - 'error'
    - devDependencies: true
  'object-curly-spacing': 'off'
  'object-curly-newline': 'off'
overrides:
  -
    files: 'tests.js'
    env:
      mocha: true
